# Generated by Django 3.2.5 on 2021-07-22 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210718_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='realtor',
            options={'permissions': [('group_realtor', 'Can eat add annonces')]},
        ),
    ]
